let suggestions = [
    "Add",
    "Age",
    "Aunt",
    "Alive",
    "Alone",
    "Apple",
    "Actor",
    "Blogger",
    "Bollywood",
    "Channel",
    "CodingLab",
    "YouTube",
    "YouTuber",
    "YouTube Channel",
    "Vlogger",
    "Vechiles",
    "Facebook",
    "Freelancer",
    "Facebook Page",
    "Designer",
    "Developer",
    "Web Designer",
    "Web Developer",
    "Login Form in HTML & CSS",
    "How to learn HTML & CSS",
    "How to learn JavaScript",
    "How to become Freelancer",
    "How to become Web Designer",
    "How to start Gaming Channel",
    "How to start YouTube Channel",
    "What does HTML stands for?",
    "What does CSS stands for?",
    "whatsapp web",
    "youtube",
    "google",
    "sarkari result",
    "flipkart",
    "satta",
    "amazon",
    "gmail",
    "instagram",
    "cricbuzz",
    "translate",
    "matka",
    "lottery sambad",
    "google translate",
    "speed test",
    "uidai",
    "facebook",
    "fb",
    "hotstar",
    "english to hindi",
    "satta matka",
    "movierulz",
    "sbi online",
    "whatsapp",
    "weather",
    "pm kisan",
    "epfo",
    "netflix",
    "web whatsapp",
    "hdfc", 
    "netbanking",

];   